### PR TITLE
[JSP-REMOVAL] Removed the jsp webapp entirely

### PR DESCRIPTION
**Pull request by TheGreatJoules**
Removed the jsp webapp entirely by refactoring the sm-shop application by clearing the SpringBootServletInitializer from its context. Removed the xml servlet configurations, updated the core filters, removed unused servlet exceptions and unused servlet imports, removed shop tags, and all related maven dependencies.

With the following changes, I'm able to successful build and run without the jsps

### CODE REVIEW

**Comment by shopizer-ecommerce** [comment]
Would you mind changing your pr to 2.0.alpha branch ?

**Comment by shopizer-ecommerce** [comment]
my bad 3.0.alpha

**Comment by TheGreatJoules** [comment]
Yeah sounds good, however I believe it has already been changed to the 3.0 alpha branch.

**Comment by TheGreatJoules** [comment]
Yeah sounds good, however I believe it has already been changed to the 3.0 alpha branch.

**Comment by TheGreatJoules** [comment]
I will also send out a revision to the commit to address the conflicting files error check for ``sm-shop/files/store/DownlaodRepository.dat`` by unstaging the changes when I originally added it.

**Comment by TheGreatJoules** [comment]
I am closing my pull request and will delete my forked branch because I have pulled from the latest master branch and pushed changes onto it that need to be reverted. I will instead fork from 3.0.alpha and apply my changes on that branch for a clean and simple code change for review.

**Comment by shopizer-ecommerce** [comment]
Thanks @TheGreatJoules !!!

**Pull request closed without merging**
