### PR TITLE
fix bug :org.hibernate.LazyInitializationException: failed to lazily …

### PR DESCRIPTION
**Pull request by t0rjan**
…initialize a collection of role: com.salesmanager.core.model.merchant.MerchantStore.languages, could not initialize proxy - no Session at

url :/admin/store/editStore.html?id=103

### CODE REVIEW

**Comment by t0rjan** [comment]
issue:https://github.com/shopizer-ecommerce/shopizer/issues/275

**Comment by shopizer-ecommerce** [comment]
Ok great, i'll push it soon thanks !

**Comment by t0rjan** [comment]
I hope you use Google's code style checker, checkstyle google.

**Comment by t0rjan** [comment]
This way our collaboration will become more enjoyable.

**Comment by shopizer-ecommerce** [comment]
Sorry for the delay, we are getting back on all of this, thanks for the recommendations

**Pull request closed without merging**
