### PR TITLE
[enhancement] added Lombook dependency

### PR DESCRIPTION
**Pull request by DzmitryNev**
@shopizer-ecommerce
@umeshawasthi

### CODE REVIEW

**Comment by shopizer-ecommerce** [comment]
Thanks, will check rest api error handling

**Comment by shopizer-ecommerce** [comment]
Hi DzmitryNev,
I merged the new code to master and played around with it, although annotations for code can be helpful i found that in an IDE perspective (eclipse in my case) some additional steps have to be made to prevent compilation errors to be shown. I did not do the necessary this time, the reason being that since we offer an open source software there are some technology we need to think carefully before adoption. We are trying to keep the things minimal, we used previous similar technology and got flooded of people asking how come errors were show or how classes were generated and so on even if documentation described everything. I will put lombok on hold for now since we are full speed on master branch, i will create a fork for taking the time to evaluate.

Your error handling solution is brillant and we will keep the way errors are managed.

**Comment by DzmitryNev** [comment]
Hi @shopizer-ecommerce,
For eclipse lombok support: https://projectlombok.org/setup/eclipse 
1. Download lombok.jar
2. Double-click lombok.jar (downloadable from this site, or from your maven repository; it's the same jar). This starts the eclipse installer which will find eclipse (and eclipse variants as listed above), and offers to install lombok into these eclipse installations
image

3. Restart eclipse

For idea community: 
https://plugins.jetbrains.com/plugin/6317-lombok-plugin
1. install lombok plugin ( Settings -> Plugins -> lombok)
2. Enable annotation processing (Build, Excution, Deployment -> Compiler -> Annotation Processors -> Enable annotation processing)
image
3. Restart idea

**Comment by shopizer-ecommerce** [comment]
Hi @DzmitryNev we are looking for help on our next release, would you be interested in a closer collaboration ? If so here is our contact form http://www.shopizer.com/contact.html will add you to our slack chat ops

**Pull request merged**
